---

  - name: copy configuration file
    copy:
      src: "{{path}}/jenkins.conf"
      dest: /etc/nginx/conf.d/jenkins.conf

  - name: update jenkins.conf
    lineinfile:
      dest: /etc/nginx/conf.d/jenkins.conf
      regexp: "{{item.regexp}}"
      line: "{{item.line}}"
    with_items:
      - { regexp: 'server_name', line: "    server_name {{my_sever_name}};"}

  - name: restart nginx
    service:
      name: nginx
      state: restarted
