---

- name: Run nginx
  hosts: aws
  gather_facts: false
  remote_user: ec2-user
  become: true
  become_method: sudo
  vars_files:
    - variables.yml
    - ec2_variables.yml
  roles:
    - jenkins_start
    - nginx_start
    - nginx_jenkins_configuration
